# Generated by Django 4.0.4 on 2022-04-14 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0002_alter_customer_sales_contact_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('N', 'Not started'), ('I', 'In progress'), ('C', 'Closed')], default='Not started', max_length=16)),
                ('attendees', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='crm.contract')),
                ('support_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_contact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
