# Generated by Django 4.0.4 on 2022-04-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='amount',
        ),
    ]
