# Generated by Django 4.0.4 on 2022-04-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_member_is_admin_member_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.CharField(choices=[('P', 'Support'), ('S', 'Sales')], max_length=64),
        ),
    ]
